version: '3.7'
services:
  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4572:4572 # S3
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./docker:/docker-entrypoint-initaws.d
